apiVersion: apps/v1
kind: Deployment
metadata:
  name: landing-page
  labels:
    app: landing-page
spec:
  replicas: 3
  selector:
    matchLabels:
      app: landing-page
  template:
    metadata:
      labels:
        app: landing-page
    spec:
      containers:
      - name: landing-page
        image: highsaltlevels/landing-page:latest-arm64
        env:
        - name: PYTHONUNBUFFERED
          value: "0"
        command:
        - python3
        - /opt/landing-page
        imagePullPolicy: Always
