---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: landing-page
  labels:
    app: landing-page
spec:
  replicas: 2
  selector:
    matchLabels:
      app: landing-page
  template:
    metadata:
      labels:
        app: landing-page
    spec:
      containers:
      - name: landing-page
        image: highsaltlevels/landing-page:latest
        imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: landing-page
  name: landing-page
  namespace: landing-page
spec:
  externalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 50000
    protocol: TCP
    targetPort: 8080
    nodePort: 32069
  selector:
    app: landing-page
  sessionAffinity: None
  type: NodePort
