---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: pod-reader
automountServiceAccountToken: false
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  namespace: status
  name: pod-reader
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: pod-reader
  namespace: status
subjects:
- kind: ServiceAccount
  name: pod-reader
  namespace: status
roleRef:
  kind: ClusterRole
  name: pod-reader
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pod-reader
  labels:
    app: pod-reader
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pod-reader
  template:
    metadata:
      labels:
        app: pod-reader
    spec:
      containers:
      - name: pod-reader
        image: highsaltlevels/pod-reader:latest
        imagePullPolicy: Always
      automountServiceAccountToken: true
      serviceAccountName: pod-reader
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: pod-reader
  name: pod-reader
spec:
  externalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 42069
    targetPort: 42069
    protocol: TCP
    nodePort: 31069
  selector:
    app: pod-reader
  sessionAffinity: None
  type: NodePort
