apiVersion: v1
kind: Service
metadata:
  labels:
    app: landing-page
  name: landing-page
  namespace: landing-page
spec:
  externalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 50000
    protocol: TCP
    targetPort: 80
  selector:
    app: landing-page
  sessionAffinity: None
  type: NodePort
